controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.65
    wheel_radius: 0.05
    publish_rate: 50.0
    use_stamped_vel: false
    open_loop: false
    enable_odom_tf: false
    base_frame_id: base_link
    odom_frame_id: odom
